# Revan Kumar Sanganamoni AIML LetsUpgrade

Day10 Assignment

In [51]:
import numpy as np
x = np.array([3, 5,8,1,6])
y = np.array([2, 5,4,6,6])
print("Original numbers:")
print("array 1 is: ",x)
print("array 2 is: ",y)
print("Comparison of greater than is: ",np.greater(x, y))
print("\n")
print(x,y)
print("Comparison of greater than_equal is: ",np.greater_equal(x, y))
print("\n")
print(x,y)
print("Comparison of less than is: ",np.less(x, y))
print("\n")
print(x,y)
print("Comparison of less than_equal is: ",np.less_equal(x, y))

Original numbers:
array 1 is:  [3 5 8 1 6]
array 2 is:  [2 5 4 6 6]
Comparison of greater than is:  [ True False  True False False]


[3 5 8 1 6] [2 5 4 6 6]
Comparison of greater than_equal is:  [ True  True  True False  True]


[3 5 8 1 6] [2 5 4 6 6]
Comparison of less than is:  [False False False  True False]


[3 5 8 1 6] [2 5 4 6 6]
Comparison of less than_equal is:  [False  True False  True  True]


In [39]:
import numpy as np
np.greater([6,2],[5,4])


#here,6 is >  5
#     2 is !> 4

array([ True, False])

In [30]:
a=[6,2]
b=[5,4]
print(a>b)
print(a<b)

True
False


In [36]:
np.greater_equal([5,1,4,3],[2,3,3,4])
#here,5 is >= 2
#       1 is !>= 3
#       4 is >=3
#       3 is !>= 4

array([ True, False,  True, False])

In [38]:
import numpy as np
np.less([6,2],[5,4])
# here, 6 !< 5
#       2 <  4

array([False,  True])

In [42]:
np.less_equal([5,1,4,3],[2,3,3,4])
#here,5 is !<= 2
#       1 is <= 3
#       4 is !<=3
#       3 is <= 4

array([False,  True, False,  True])

In [66]:
import numpy as np
array=np.zeros(10)
print("array of zeros is: ",array)
array=np.ones(10)
print("array of ones is:  ",array)
array=np.ones(10)*5
print("array of fives is: ",array)



array of zeros is:  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
array of ones is:   [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
array of fives is:  [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [69]:
import numpy as np
x = np.array([[3,7],[4,9]])
print("Original array:")
print(x)
print("Sum of all elements:")
print(np.sum(x))
print("Sum of each column:")
print(np.sum(x, axis=0))
print("Sum of each row:")
print(np.sum(x, axis=1))


Original array:
[[3 7]
 [4 9]]
Sum of all elements:
23
Sum of each column:
[ 7 16]
Sum of each row:
[10 13]


In [73]:
import numpy as np
x=np.array([2,5])
y=np.array([3,6])
print(x,y)
print("add of elements is: ",x+y)
print("\n")
print(x,y)
print("sub of elements is: ",x-y)
print("\n")
print(x,y)
print("multiply of elements is: ",x*y)
print("\n")
print(x,y)
print("divide of elements is: ",x/y)


[2 5] [3 6]
add of elements is:  [ 5 11]


[2 5] [3 6]
sub of elements is:  [-1 -1]


[2 5] [3 6]
multiply of elements is:  [ 6 30]


[2 5] [3 6]
divide of elements is:  [0.66666667 0.83333333]


In [84]:
import numpy as np
print("pi value is: ",np.pi)
print("to find degree of trignometric values is: ", np.pi/180)
print("\n")
print("sine: array of angles given in degrees")
print(np.sin(np.array((0., 30., 45., 60., 90.)) * np.pi / 180.))
print("\n")
print("cosine: array of angles given in degrees")
print(np.cos(np.array((0., 30., 45., 60., 90.)) * np.pi / 180.))
print("\n")
print("tangent: array of angles given in degrees")
print(np.tan(np.array((0., 30., 45., 60., 90.)) * np.pi / 180.))

pi value is:  3.141592653589793
to find degree of trignometric values is:  0.017453292519943295


sine: array of angles given in degrees
[0.         0.5        0.70710678 0.8660254  1.        ]


cosine: array of angles given in degrees
[1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]


tangent: array of angles given in degrees
[0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]


In [95]:
import pandas as panda
import numpy as np

stud_data  = {'NameofStud': ['Revan', 'Vinod', 'Chandrika', 'AbhiRam', 'SiriChandhana', 'Yashika Pravardhini', 'Chabby'],
        'score': [24, 29, 26, np.nan, 3, 1.5, 0.1],
        'attempts': [1, 3, 2, 4, 2, 1, 0],
        'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes','yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g']

dataframe = panda.DataFrame(stud_data , index=labels)
print(dataframe)

            NameofStud  score  attempts qualify
a                Revan   24.0         1     yes
b                Vinod   29.0         3      no
c            Chandrika   26.0         2     yes
d              AbhiRam    NaN         4      no
e        SiriChandhana    3.0         2      no
f  Yashika Pravardhini    1.5         1     yes
g               Chabby    0.1         0     yes


In [96]:
print("Selecting the name and score columns from above dataframe : \n\n",dataframe[['NameofStud','score']])

Selecting the name and score columns from above dataframe : 

             NameofStud  score
a                Revan   24.0
b                Vinod   29.0
c            Chandrika   26.0
d              AbhiRam    NaN
e        SiriChandhana    3.0
f  Yashika Pravardhini    1.5
g               Chabby    0.1


In [97]:
import pandas as panda

cse = panda.DataFrame({
        'student_id': ['S1', 'S2', 'S3', 'S4', 'S5'],
         'name': ['Revan', 'Deva', 'Vinod', 'Teja', 'AbhiRam'], 
        'marks': [200, 210, 190, 222, 199]})

it= panda.DataFrame({
        'student_id': ['S4', 'S5', 'S6', 'S7', 'S8'],
        'name': ['Chandrika', 'Yashika Pravardhini', 'Siri Chandana', 'Chabby', 'Gayathri'], 
        'marks': [201, 200, 198, 219, 201]})

print("Original DataFrames : ")
print("\n")
print(cse)
print("-------------------------------------")
print(it)
print("\nJoin the said two dataframes along rows:")
result_data = panda.concat([cse,it])
print(result_data)

Original DataFrames : 


  student_id     name  marks
0         S1    Revan    200
1         S2     Deva    210
2         S3    Vinod    190
3         S4     Teja    222
4         S5  AbhiRam    199
-------------------------------------
  student_id                 name  marks
0         S4            Chandrika    201
1         S5  Yashika Pravardhini    200
2         S6        Siri Chandana    198
3         S7               Chabby    219
4         S8             Gayathri    201

Join the said two dataframes along rows:
  student_id                 name  marks
0         S1                Revan    200
1         S2                 Deva    210
2         S3                Vinod    190
3         S4                 Teja    222
4         S5              AbhiRam    199
0         S4            Chandrika    201
1         S5  Yashika Pravardhini    200
2         S6        Siri Chandana    198
3         S7               Chabby    219
4         S8             Gayathri    201


In [106]:
import pandas as panda

cse = panda.DataFrame({
        'student_id': [np.nan, 'S2', 'S3', np.nan, 'S5'],
         'name': ['Revan', np.nan, 'vinod', 'Teja', 'AbhiRam'], 
        'marks': [200, 210,np.nan, 222,np.nan]})

it= panda.DataFrame({
        'student_id': ['S4', np.nan,'S6',np.nan,np.nan],
        'name': ['Chandrika', 'Yashika Pravardhini', 'Siri Chandana', 'Chabby', np.nan], 
        'marks': [np.nan, 200,np.nan, 219, 201]})

print("Original DataFrames : ")
print("\n")
print(cse)
print("-------------------------------------")
print(it)
print("\nJoin the said two dataframes along rows:")
result_data = panda.concat([cse,it])
dataframes=result_data
print(dataframes)
print("\n")
print("Missed values are : ")
print(dataframes.isna())

Original DataFrames : 


  student_id     name  marks
0        NaN    Revan  200.0
1         S2      NaN  210.0
2         S3    vinod    NaN
3        NaN     Teja  222.0
4         S5  AbhiRam    NaN
-------------------------------------
  student_id                 name  marks
0         S4            Chandrika    NaN
1        NaN  Yashika Pravardhini  200.0
2         S6        Siri Chandana    NaN
3        NaN               Chabby  219.0
4        NaN                  NaN  201.0

Join the said two dataframes along rows:
  student_id                 name  marks
0        NaN                Revan  200.0
1         S2                  NaN  210.0
2         S3                vinod    NaN
3        NaN                 Teja  222.0
4         S5              AbhiRam    NaN
0         S4            Chandrika    NaN
1        NaN  Yashika Pravardhini  200.0
2         S6        Siri Chandana    NaN
3        NaN               Chabby  219.0
4        NaN                  NaN  201.0


Missed values are : 
 

In [107]:
import pandas as panda
disp = panda.Series([10, 9, 2, 13, 10])
print(disp)

0    10
1     9
2     2
3    13
4    10
dtype: int64
